print("Doctor Who Festival - Price Calculator")
print("note:enter 0if none")
individual=int(input("please enter individual:"))
under16=int(input("please entere under16 family:"))
totalfamilies=int(input("please enter totalfamilies:"))
# print("Enter total number of individua:l",individual)
# print("Enter total number of under 16s:",under16)
# print("Enter total number of families:",totalfamilies)
print("Category Price Breakdown:")
print("Price is",individual*68,"for",individual)
print("Price is",under16*32.25,"for",under16)
print("Price is",totalfamilies*42.75,"for",totalfamilies)
print("total persons",individual+under16+totalfamilies*4)
print("Total Event Price is",individual*68+under16*32.25+totalfamilies*42.75)